name: if-part2

on: 

  workflow_dispatch:
       inputs :
          condition:
            description: "condition"

  

jobs: 

  reusable-checkout: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@v3 

    - name: list the repo files 

      run: ls 
    
    - name: paras
      if: ${{ inputs.condition == 'true'}}
      run: echo "hy paras"
